
CREATE TABLE MEMBER(

    ID VARCHAR2(50),
    PASS VARCHAR2(50),
    NAME VARCHAR2(20),
    REG_DATE DATE
) SEGMENT CREATION DEFERRED
PCTREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
NNOCOMPRESS LOGGING
TABLESPACE "USERS";