spring.application.name=JPAEX
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/bootex
spring.datasource.username=jason
spring.datasource.password=1234

# 프로젝트 실행시에 자동으로 DDL(create, alter, drop)을 생성할지 여부에 관련된 설정이다.
# 값으로는 create, update 등이 있으며 create은 매번 테이블을 새롭게 생성하는 것이고,
# update는 엔티티에 변경이 있는 상태, 즉 테이블과 데이터가 차이나는 상태에만 새롭게 테이블을 생성한다.
spring.jpa.hibernate.ddl-auto=update

# SQL 실행시 콘솔에 출력 여부를 결정하는 설정
spring.jpa.properties.hibernate.format_sql=true
# JPA 처리시에 발생하는 SQL 출력 여부를 결정
spring.jpa.show-sql=true