SELECT USER FROM DUAL;

CREATE TABLE PRACTICE_USERS (
    USER_ID NUMBER NOT NULL,
    NAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(50) UNIQUE,
    JOIN_DATE DATE DEFAULT SYSDATE,
    ROLE VARCHAR2(20) DEFAULT 'USER',
    CONSTRAINT practice_users_pk PRIMARY KEY (USER_ID)
);

CREATE TABLE TEMP_USERS(
    NAME VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(50)
);

CREATE SEQUENCE USER_SEQ
START WITH 1
INCREMENT BY 1
NOCYCLE;

COMMIT;